//! On-theme ASCII image rendering.
//!
//! The retro rule is "stay on theme at all times" — there is no raw `<img>` in
//! the BBS. Every image surface (banner, pod File Base, Message Base posts)
//! becomes ASCII art. The image→ASCII conversion happens **server-side**:
//!
//! * the preview-worker exposes
//!   `GET /ascii?url=<imgurl>&cols=<n>&ramp=<standard|blocks|dense>`, and
//! * the pod-worker serves any pod image resource as the same fragment when
//!   requested with `?format=ascii`.
//!
//! Both return an HTML fragment
//! `<pre class="ascii-img" aria-hidden="true"><span class="pN">…</span>…</pre>`
//! whose `pN` cells (p0..p7) are theme-agnostic phosphor levels; `assets/bbs.css`
//! recolours them per active theme via `color-mix` on the theme vars.
//!
//! This module is the CLIENT side: [`AsciiImg`] fetches the fragment for a given
//! image URL (through the preview endpoint, or directly with `?format=ascii` for
//! pod-hosted images) and injects it. The pure URL/parsing helpers are
//! unit-tested on the native target; the `fetch` itself is wasm-only.

use leptos::prelude::*;

use crate::config::BbsConfig;

/// Default column width for the ASCII grid when a caller doesn't specify one.
pub const DEFAULT_COLS: u32 = 80;

/// Async load state for a single ASCII image fragment.
///
/// `Loaded` is only constructed on wasm (after a successful fetch); on the
/// native target the fetch is compiled out, so silence the dead-code lint there.
#[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
#[derive(Clone, Debug, PartialEq, Eq)]
enum AsciiState {
    /// Fetch in flight.
    Loading,
    /// Server-rendered HTML fragment ready to inject.
    Loaded(String),
    /// Fetch failed / no endpoint / wrong content-type.
    Error,
}

/// Render an image as on-theme ASCII art.
///
/// On mount it fetches the server-rendered phosphor fragment for `src` and
/// injects it. While loading it shows `[ loading ascii … ]`; on any error it
/// shows `[ image unavailable ]`. Endpoints come from [`BbsConfig`] in context
/// (`preview_api` for arbitrary URLs, `pod_api` for pod-hosted images).
#[component]
pub fn AsciiImg(
    /// Image URL to render.
    src: String,
    /// ASCII grid width in columns.
    #[prop(default = DEFAULT_COLS)]
    cols: u32,
    /// Phosphor ramp: `standard`, `blocks`, or `dense`.
    #[prop(default = String::from("standard"))]
    ramp: String,
) -> impl IntoView {
    let cfg = use_context::<StoredValue<BbsConfig>>().expect("config");
    let (preview_api, pod_api) = cfg.with_value(|c| (c.preview_api.clone(), c.pod_api.clone()));
    // Resolve a root-relative src (e.g. a zone banner "/images/heroes/x.webp")
    // to an absolute URL — the /ascii endpoint fetches server-side and cannot
    // resolve a client-relative path.
    #[cfg(target_arch = "wasm32")]
    let src = make_absolute(&current_origin(), &src);
    let fetch_url = ascii_fetch_url(&preview_api, &pod_api, &src, cols, &ramp);

    let state = RwSignal::new(if fetch_url.is_some() {
        AsciiState::Loading
    } else {
        AsciiState::Error
    });

    if let Some(url) = fetch_url {
        #[cfg(target_arch = "wasm32")]
        wasm_bindgen_futures::spawn_local(async move {
            match fetch_ascii(&url).await {
                Ok(html) => state.set(AsciiState::Loaded(html)),
                Err(_) => state.set(AsciiState::Error),
            }
        });
        #[cfg(not(target_arch = "wasm32"))]
        let _ = url;
    }

    move || match state.get() {
        AsciiState::Loading => view! {
            <pre class="ascii-img ascii-img-status">"[ loading ascii … ]"</pre>
        }
        .into_any(),
        AsciiState::Error => view! {
            <pre class="ascii-img ascii-img-status">"[ image unavailable ]"</pre>
        }
        .into_any(),
        // The fragment is server-generated by our own workers and already
        // HTML-escaped (only <pre>/<span class="pN"> structure); inject it.
        AsciiState::Loaded(html) => view! {
            <div class="ascii-img-wrap" inner_html=html></div>
        }
        .into_any(),
    }
}

/// Is `src` a resource hosted under the configured pod API base?
pub fn is_pod_url(pod_api: &str, src: &str) -> bool {
    !pod_api.is_empty() && src.starts_with(pod_api.trim_end_matches('/'))
}

/// Resolve a possibly root-relative URL against `origin`. Absolute http(s) URLs
/// and empty strings pass through unchanged; `"/path"` and `"path"` are joined
/// onto the origin. The `/ascii` endpoint fetches server-side, so the URL it
/// receives must be absolute.
pub fn make_absolute(origin: &str, src: &str) -> String {
    let s = src.trim();
    if s.is_empty() || s.starts_with("http://") || s.starts_with("https://") {
        s.to_string()
    } else {
        format!(
            "{}/{}",
            origin.trim_end_matches('/'),
            s.trim_start_matches('/')
        )
    }
}

/// The current document origin (wasm), e.g. `https://dreamlab-ai.com`.
#[cfg(target_arch = "wasm32")]
fn current_origin() -> String {
    web_sys::window()
        .and_then(|w| w.location().origin().ok())
        .unwrap_or_default()
}

/// Build the URL to fetch the ASCII fragment for `src`.
///
/// * Pod-hosted images are fetched directly with `?format=ascii` (plus
///   `cols`/`ramp`), since the pod-worker renders them itself.
/// * Everything else goes through the preview-worker's `/ascii` endpoint with
///   the image URL percent-encoded.
///
/// Returns `None` when neither endpoint can serve the image (no preview API
/// configured and the URL isn't pod-hosted), so the caller renders the
/// `[ image unavailable ]` placeholder.
pub fn ascii_fetch_url(
    preview_api: &str,
    pod_api: &str,
    src: &str,
    cols: u32,
    ramp: &str,
) -> Option<String> {
    if src.trim().is_empty() {
        return None;
    }
    if is_pod_url(pod_api, src) {
        let sep = if src.contains('?') { '&' } else { '?' };
        Some(format!("{src}{sep}format=ascii&cols={cols}&ramp={ramp}"))
    } else if !preview_api.is_empty() {
        let base = preview_api.trim_end_matches('/');
        Some(format!(
            "{base}/ascii?url={}&cols={cols}&ramp={ramp}",
            encode_uri_component(src)
        ))
    } else {
        None
    }
}

/// Whether a filename looks like a renderable raster image.
pub fn is_image_name(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    let stem = lower.split(['?', '#']).next().unwrap_or(&lower);
    matches!(
        stem.rsplit('.').next(),
        Some("png" | "jpg" | "jpeg" | "gif" | "webp" | "bmp")
    ) && stem.contains('.')
}

/// Whether `s` is an absolute http(s) image URL.
pub fn is_image_url(s: &str) -> bool {
    let lower = s.to_ascii_lowercase();
    if !(lower.starts_with("http://") || lower.starts_with("https://")) {
        return false;
    }
    is_image_name(&lower)
}

/// Extract image URLs from free-form post content.
///
/// Splits on whitespace, strips wrapping punctuation/markdown delimiters, and
/// keeps tokens that are absolute http(s) URLs ending in a known image
/// extension. De-duplicated, order-preserving.
pub fn extract_image_urls(content: &str) -> Vec<String> {
    const TRIM: &[char] = &[
        '(', ')', '[', ']', '<', '>', '{', '}', '"', '\'', '`', ',', '.', '!', '?', ';', ':', '|',
        '*', '~',
    ];
    let mut out: Vec<String> = Vec::new();
    for tok in content.split_whitespace() {
        let url = tok.trim_matches(TRIM);
        if is_image_url(url) && !out.iter().any(|u| u == url) {
            out.push(url.to_string());
        }
    }
    out
}

/// Percent-encode a string the way JavaScript's `encodeURIComponent` does:
/// every byte except the unreserved set `A-Z a-z 0-9 - _ . ! ~ * ' ( )`.
fn encode_uri_component(s: &str) -> String {
    fn hex(n: u8) -> char {
        match n {
            0..=9 => (b'0' + n) as char,
            _ => (b'A' + (n - 10)) as char,
        }
    }
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'A'..=b'Z'
            | b'a'..=b'z'
            | b'0'..=b'9'
            | b'-'
            | b'_'
            | b'.'
            | b'!'
            | b'~'
            | b'*'
            | b'\''
            | b'('
            | b')' => out.push(b as char),
            _ => {
                out.push('%');
                out.push(hex(b >> 4));
                out.push(hex(b & 0x0f));
            }
        }
    }
    out
}

/// Fetch a server-rendered ASCII fragment. Wasm-only (uses the Fetch API).
///
/// Only injects the body when the response is `text/html` from our own workers;
/// the fragment is server-generated and already HTML-escaped.
#[cfg(target_arch = "wasm32")]
async fn fetch_ascii(url: &str) -> Result<String, String> {
    use wasm_bindgen::JsCast;
    use wasm_bindgen_futures::JsFuture;

    let init = web_sys::RequestInit::new();
    init.set_method("GET");
    init.set_mode(web_sys::RequestMode::Cors);
    if let Ok(headers) = web_sys::Headers::new() {
        let _ = headers.set("Accept", "text/html");
        init.set_headers(&headers);
    }
    let request = web_sys::Request::new_with_str_and_init(url, &init)
        .map_err(|e| format!("bad request: {e:?}"))?;
    let win = web_sys::window().ok_or("no window")?;
    let resp_val = JsFuture::from(win.fetch_with_request(&request))
        .await
        .map_err(|e| format!("fetch failed: {e:?}"))?;
    let resp: web_sys::Response = resp_val
        .dyn_into()
        .map_err(|_| "not a Response".to_string())?;
    if !resp.ok() {
        return Err(format!("HTTP {}", resp.status()));
    }
    let ctype = resp
        .headers()
        .get("content-type")
        .ok()
        .flatten()
        .unwrap_or_default();
    if !ctype.to_ascii_lowercase().contains("text/html") {
        return Err(format!("unexpected content-type: {ctype}"));
    }
    let text_val = JsFuture::from(resp.text().map_err(|e| format!("{e:?}"))?)
        .await
        .map_err(|e| format!("read failed: {e:?}"))?;
    Ok(text_val.as_string().unwrap_or_default())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pod_url_detection() {
        assert!(is_pod_url(
            "https://pods.example.com",
            "https://pods.example.com/pods/ab/x.png"
        ));
        assert!(is_pod_url(
            "https://pods.example.com/",
            "https://pods.example.com/pods/ab/x.png"
        ));
        assert!(!is_pod_url("", "https://pods.example.com/pods/ab/x.png"));
        assert!(!is_pod_url(
            "https://pods.example.com",
            "https://cdn.other.com/x.png"
        ));
    }

    #[test]
    fn pod_image_fetches_with_format_ascii() {
        let url = ascii_fetch_url(
            "https://preview.example.com",
            "https://pods.example.com",
            "https://pods.example.com/pods/ab/cat.png",
            72,
            "standard",
        )
        .expect("url");
        assert_eq!(
            url,
            "https://pods.example.com/pods/ab/cat.png?format=ascii&cols=72&ramp=standard"
        );
    }

    #[test]
    fn pod_image_with_query_uses_ampersand() {
        let url = ascii_fetch_url(
            "https://preview.example.com",
            "https://pods.example.com",
            "https://pods.example.com/pods/ab/cat.png?v=2",
            64,
            "blocks",
        )
        .expect("url");
        assert_eq!(
            url,
            "https://pods.example.com/pods/ab/cat.png?v=2&format=ascii&cols=64&ramp=blocks"
        );
    }

    #[test]
    fn external_image_routes_through_preview_and_is_encoded() {
        let url = ascii_fetch_url(
            "https://preview.example.com/",
            "https://pods.example.com",
            "https://cdn.other.com/a b.png?x=1&y=2",
            80,
            "standard",
        )
        .expect("url");
        assert_eq!(
            url,
            "https://preview.example.com/ascii?url=https%3A%2F%2Fcdn.other.com%2Fa%20b.png%3Fx%3D1%26y%3D2&cols=80&ramp=standard"
        );
    }

    #[test]
    fn no_endpoint_for_external_image_is_none() {
        assert!(ascii_fetch_url(
            "",
            "https://pods.example.com",
            "https://cdn.other.com/x.png",
            80,
            "standard"
        )
        .is_none());
        assert!(ascii_fetch_url("", "", "  ", 80, "standard").is_none());
    }

    #[test]
    fn encode_matches_encode_uri_component() {
        assert_eq!(encode_uri_component("a b"), "a%20b");
        assert_eq!(encode_uri_component("x=1&y=2"), "x%3D1%26y%3D2");
        assert_eq!(
            encode_uri_component("https://h/p.png"),
            "https%3A%2F%2Fh%2Fp.png"
        );
        // Unreserved set is preserved verbatim.
        assert_eq!(encode_uri_component("-_.!~*'()AzZ09"), "-_.!~*'()AzZ09");
    }

    #[test]
    fn make_absolute_resolves_root_relative_only() {
        let o = "https://dreamlab-ai.com";
        assert_eq!(
            make_absolute(o, "/images/heroes/lake.webp"),
            "https://dreamlab-ai.com/images/heroes/lake.webp"
        );
        assert_eq!(
            make_absolute(o, "images/x.png"),
            "https://dreamlab-ai.com/images/x.png"
        );
        // Already absolute / empty pass through untouched.
        assert_eq!(
            make_absolute(o, "https://cdn.other.com/x.png"),
            "https://cdn.other.com/x.png"
        );
        assert_eq!(make_absolute(o, "  "), "");
        // Trailing slash on origin is normalised.
        assert_eq!(make_absolute("https://h/", "/a.png"), "https://h/a.png");
    }

    #[test]
    fn image_name_classification() {
        assert!(is_image_name("photo.PNG"));
        assert!(is_image_name("a.jpeg"));
        assert!(is_image_name("b.webp"));
        assert!(is_image_name("c.png?cache=1"));
        assert!(!is_image_name("notes.txt"));
        assert!(!is_image_name("README"));
        assert!(!is_image_name("png"));
    }

    #[test]
    fn image_url_requires_http_scheme() {
        assert!(is_image_url("https://x.com/a.png"));
        assert!(is_image_url("http://x.com/a.JPG"));
        assert!(!is_image_url("ftp://x.com/a.png"));
        assert!(!is_image_url("/local/a.png"));
        assert!(!is_image_url("https://x.com/page"));
    }

    #[test]
    fn extract_urls_strips_punctuation_and_dedups() {
        let content =
            "see (https://x.com/a.png) and https://x.com/b.jpg! also https://x.com/a.png again";
        let urls = extract_image_urls(content);
        assert_eq!(
            urls,
            vec![
                "https://x.com/a.png".to_string(),
                "https://x.com/b.jpg".to_string()
            ]
        );
    }

    #[test]
    fn extract_urls_ignores_non_images() {
        let urls = extract_image_urls("hello https://x.com/page and a.png without scheme");
        assert!(urls.is_empty());
    }
}
